# Generated by Django 5.0.7 on 2024-08-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='tittle',
            new_name='title',
        ),
    ]
